"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-24

Hand-authored (not autogenerated — no working Python interpreter was
available in the environment that scaffolded this project to run
`alembic revision --autogenerate` against a live DB). Verify this applies
cleanly against a fresh `recruitfast` database before relying on it.
"""
from alembic import op
import sqlalchemy as sa

from app.core.database import Base
from app.models import *  # noqa: F401,F403 — populates Base.metadata

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)

    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS citext")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
