"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-24

Hand-authored (not autogenerated — no working Python interpreter was
available in the environment that scaffolded this project to run
`alembic revision --autogenerate` against a live DB).

This intentionally always creates the CURRENT full schema (every table,
every column, on whatever the models look like right now), not a
point-in-time snapshot — that was the original design (see the git
history of this docstring). The tradeoff: every migration from 0002
onward, at the moment it was first written, was adding something not
yet reflected in models.py. Once a later migration's change (a new
column, a new table) gets folded back into the model file it belongs
to, this migration's create_all() picks it up too, and the migration
that originally introduced it becomes redundant, since a genuinely
fresh database now gets that column/table from here instead. That
stopped being harmless once enough columns accumulated: a truly fresh
`alembic upgrade head` started failing with "column already exists" a
few migrations in.

Fixed 2026-08-26 by having this migration also set up the one thing
create_all() can't express, row-level security (previously spread
across migrations 0002/0006/0008/0009/0011/0012/0023 as the policies
were iterated on), and turning every migration from 0002 through 0023
into a documented no-op — see each file's docstring for what it
historically did and why it's now redundant. Revision IDs and the
down_revision chain are unchanged, so a database that already ran the
real version of those migrations (this project's own dev database
included) is unaffected; only a from-scratch install's path changes.
Any future schema change still gets its own new migration, same as
always — this only retires the already-applied history up through
0023, it doesn't change how migrations work going forward.
"""
from alembic import op
import sqlalchemy as sa

from app.core.database import Base
from app.models import *  # noqa: F401,F403 — populates Base.metadata

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

# Every table that ever got row-level security across migrations
# 0002/0006/0009/0011/0012/0023 — final NULLIF-safe form from 0009,
# except `candidates` (final form from 0012) and `jobs` (also gets the
# extra permissive `public_open_jobs` policy from 0008). `clients` was
# added later, by migration 0024 (a genuinely new, non-neutered
# migration — this file always reflects current models, so it's listed
# here too for a from-scratch install). See docs/02.
_STANDARD_RLS_TABLES = [
    "jobs",
    "job_stages",
    "pipeline_placements",
    "stage_history",
    "notes",
    "candidate_documents",
    "documents",
    "job_screening_questions",
    "job_applications",
    "teams",
    "job_views",
    "clients",
]

_STANDARD_USING = (
    "current_setting('app.role', true) IS DISTINCT FROM 'superadmin' "
    "AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid"
)

_CANDIDATES_USING = (
    "current_setting('app.role', true) IS DISTINCT FROM 'superadmin' "
    "AND ("
    "  ("
    "    tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid"
    "    AND ("
    "      tenant_id NOT IN (SELECT id FROM tenants WHERE type = 'freelance_org')"
    "      OR owner_user_id = NULLIF(current_setting('app.user_id', true), '')::uuid"
    "    )"
    "  )"
    "  OR open_to_other_roles = true"
    ")"
)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)

    for table in _STANDARD_RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_STANDARD_USING}) WITH CHECK ({_STANDARD_USING})"
        )

    op.execute("ALTER TABLE candidates ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE candidates FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON candidates "
        f"USING ({_CANDIDATES_USING}) WITH CHECK ({_CANDIDATES_USING})"
    )

    # Extra permissive policy so the public job board can look up an
    # open job with no tenant/role context at all (see 0008's original
    # docstring for why a public applicant can never satisfy
    # tenant_isolation).
    op.execute(
        """
        CREATE POLICY public_open_jobs ON jobs
        FOR SELECT
        USING (status = 'open')
        """
    )

    # Added by 0025 (a real, non-neutered migration) for the databases
    # that already existed then — repeated here so a from-scratch install
    # gets the same indexes without depending on 0025 ever running for
    # real (0025 discovers it's already done via IF NOT EXISTS and no-ops).
    # Not using CREATE INDEX CONCURRENTLY here: this table has zero rows
    # at this point in a fresh install, so there's no lock contention to
    # avoid, and CONCURRENTLY can't run inside create_all()'s transaction
    # anyway.
    for table in _STANDARD_RLS_TABLES + [
        "candidates",
        "audit_log_org",
        "candidate_import_batches",
        "email_blacklist_entries",
        "pipeline_templates",
        "subscriptions",
        "users",
    ]:
        op.execute(f"CREATE INDEX IF NOT EXISTS ix_{table}_tenant_id ON {table} (tenant_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_pipeline_placements_job_id ON pipeline_placements (job_id)")


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS public_open_jobs ON jobs")
    for table in _STANDARD_RLS_TABLES + ["candidates"]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")

    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)

    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS citext")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
